import streamlit as st
import pandas as pd
import plotly.express as px
from io import BytesIO
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
import datetime
import bcrypt

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="Data Intelligence SaaS | Denis",
    page_icon="📊",
    layout="wide"
)

# ---------------- SESSION SETUP ----------------
if "users" not in st.session_state:
    st.session_state.users = {}

if "logged_in" not in st.session_state:
    st.session_state.logged_in = False

if "current_user" not in st.session_state:
    st.session_state.current_user = None

if "report_history" not in st.session_state:
    st.session_state.report_history = {}

# ---------------- AUTH SYSTEM ----------------
def register(username, password):
    hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
    st.session_state.users[username] = hashed
    st.session_state.report_history[username] = []

def login(username, password):
    if username in st.session_state.users:
        if bcrypt.checkpw(password.encode(), st.session_state.users[username]):
            st.session_state.logged_in = True
            st.session_state.current_user = username
            return True
    return False

# ---------------- LOGIN / REGISTER SCREEN ----------------
if not st.session_state.logged_in:

    st.markdown("## 🚀 Welcome to Data Intelligence SaaS")
    option = st.radio("Select Option", ["Login", "Register"])

    username = st.text_input("Username")
    password = st.text_input("Password", type="password")

    if option == "Register":
        if st.button("Create Account"):
            if username and password:
                register(username, password)
                st.success("Account created successfully. Please login.")
            else:
                st.warning("Enter username and password.")

    if option == "Login":
        if st.button("Login"):
            if login(username, password):
                st.success("Login successful")
                st.rerun()
            else:
                st.error("Invalid credentials")

    st.stop()

# ---------------- MAIN APP ----------------
st.sidebar.success(f"Logged in as: {st.session_state.current_user}")

if st.sidebar.button("Logout"):
    st.session_state.logged_in = False
    st.session_state.current_user = None
    st.rerun()

st.title("📊 Executive Data Intelligence Platform")

menu = st.sidebar.radio(
    "Navigation",
    ["Upload & Analyze", "Report History"]
)

uploaded_file = st.file_uploader("Upload CSV or Excel", type=["csv", "xlsx"])

if menu == "Upload & Analyze" and uploaded_file:

    if uploaded_file.name.endswith(".csv"):
        df = pd.read_csv(uploaded_file)
    else:
        df = pd.read_excel(uploaded_file)

    st.subheader("Dataset Overview")
    st.write(df.head())

    col1, col2 = st.columns(2)
    col1.metric("Rows", df.shape[0])
    col2.metric("Columns", df.shape[1])

    numeric_df = df.select_dtypes(include=["int64", "float64"])

    if not numeric_df.empty:
        column = st.selectbox("Select Column for Chart", numeric_df.columns)
        fig = px.bar(df, x=column)
        st.plotly_chart(fig, use_container_width=True)

        commentary = f"""
Executive Summary:
Dataset contains {df.shape[0]} records.
Primary performance metric: {column}.
Data appears structured for strategic analysis.
"""

        st.info(commentary)

        if st.button("Generate Executive PDF Report"):

            buffer = BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=A4)
            elements = []
            styles = getSampleStyleSheet()

            elements.append(Paragraph("Executive Data Intelligence Report", styles["Heading1"]))
            elements.append(Spacer(1, 12))
            elements.append(Paragraph(f"Generated by: {st.session_state.current_user}", styles["Normal"]))
            elements.append(Paragraph(f"Date: {datetime.datetime.now()}", styles["Normal"]))
            elements.append(Spacer(1, 12))
            elements.append(Paragraph(commentary, styles["Normal"]))

            doc.build(elements)
            buffer.seek(0)

            # Save to user history
            st.session_state.report_history[st.session_state.current_user].append(
                f"Report generated on {datetime.datetime.now()}"
            )

            st.download_button(
                label="Download Executive PDF",
                data=buffer,
                file_name="Executive_Report.pdf",
                mime="application/pdf"
            )

if menu == "Report History":

    st.subheader("📁 Your Generated Reports")

    history = st.session_state.report_history.get(
        st.session_state.current_user, []
    )

    if history:
        for item in history:
            st.write("•", item)
    else:
        st.info("No reports generated yet.")

st.caption("Enterprise Data Intelligence SaaS | Built by Denis")
